name: taxi_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  change_app_package_name: ^1.1.0
  flutter_local_notifications: ^15.1.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.4.5
  firebase_remote_config: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
