import 'package:taxi_app/data/models/icons/icon_type.dart';

class AppIcons {
  static IconType it = IconType.bold;
  static final String search = "assets/svg/${it.name}/search.svg";





  2_user.svg
  3_user.svg
  activity.svg
  add_user.svg
  arrow_down.svg
  arrow_down_2.svg
  arrow_down_3.svg
  arrow_down_circle.svg
  arrow_down_square.svg
  arrow_left.svg
  arrow_left_2.svg
  arrow_left_3.svg
  arrow_left_circle.svg
  arrow_left_square.svg
  arrow_right.svg
  arrow_right_2.svg
  arrow_right_3.svg
  arrow_right_circle.svg
  arrow_right_square.svg
  arrow_up.svg
  arrow_up_2.svg
  arrow_up_3.svg
  arrow_up_circle.svg
  arrow_up_square.svg
  bag.svg
  bag_2.svg
  bookmark.svg
  buy.svg
  calendar.svg
  call.svg
  call_missed.svg
  call_silent.svg
  calling.svg
  camera.svg
  category.svg
  chart.svg
  chat.svg
  close_square.svg
  danger_triangle.svg
  delete.svg
  discount.svg
  discovery.svg
  document.svg
  download.svg
  edit.svg
  edit_square.svg
  filter.svg
  filter_3.svg
  folder.svg
  game.svg
  graph.svg
  heart.svg
  hide.svg
  home.svg
  image.svg
  image_2.svg
  info_circle.svg
  info_square.svg
  location.svg
  lock.svg
  log_out.svg
  login.svg
  message.svg
  more_circle.svg
  more_square.svg
  notification.svg
  paper.svg
  paper_download.svg
  paper_fail.svg
  paper_negative.svg
  paper_plus.svg
  paper_upload.svg
  password.svg
  play.svg
  plus.svg
  profile.svg
  scan.svg
  search.svg
  send.svg
  setting.svg
  shield_done.svg
  shield_fail.svg
  show.svg
  star.svg
  swap.svg
  tick_square.svg
  ticket.svg
  ticket_star.svg
  time_circle.svg
  time_square.svg
  unlock.svg
  upload.svg
  video.svg
  voice.svg
  voice_2.svg
  volume_down.svg
  volume_off.svg
  volume_up.svg
  wallet.svg
  work.svg
}
